# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webshell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=4)),
                ('ponypath', models.CharField(max_length=255)),
                ('desk', models.CharField(max_length=255)),
                ('information', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('temp', models.CharField(max_length=255)),
            ],
        ),
    ]
